### ISSUE TITLE
Web version of schedule

### ISSUE THREAD

**Issue by nickmccurdy** [nodejs/lts-schedule#4]
I thought this repository used to have text and a rendered schedule of the current LTS releases in this readme. Could we please get something like this back? As a maintainer it's easy for me to forget which Node versions I should be supporting and I don't want to have to drop into the command line every time I check the schedule. If there isn't a web render of this yet I'd be happy to help with one.

**Comment by cjihrig** [comment]
> I thought this repository used to have text and a rendered schedule of the current LTS releases in this readme.

You're correct. You can read about what happened to the redirect in https://github.com/nodejs/Release/issues/296. The old behavior should be restored now, but technically, the repo name you want is nodejs/Release (which used to be nodejs/lts).

**Comment by nickmccurdy** [comment]
Thank you! I got confused because I had https://github.com/nodejs/lts bookmarked and it was redirecting to this repository, but now it redirects to lts-schedule so this is what I wanted.
